defaults:
  - _self_

data:
  path: "/net/acadia15a/data/kausik/imagenet_tiny"

train:
  lr: 0.0001
  batch_size: 16
  epochs: 50
  timesteps: 1000
  use_gpu_if_available: true

val:
  freq: 1

wandb:
  enable: true
  project: "diT"
  run_name: "train_0"


model:
  dim: 768
  depth: 12
  patch_size: 2

dataset:
  name: imagenet
  img_size: 256

logging:
  exp_name: "exp_dit"
